#!/bin/bash

if [ -z ${NEWRELIC_LICENSE_KEY} ]; then
  echo "Variable NEWRELIC_LICENSE_KEY not set. Exiting."
  exit 1
fi
nrsysmond-config --set license_key=${NEWRELIC_LICENSE_KEY}

NRSYSMOND_PARAMS="-F -l /dev/stdout"

if [ -z ${NEWRELIC_HOSTNAME} ]; then
  echo "Warning: Variable NEWRELIC_HOSTNAME not set. Using default HOSTNAME: '${HOSTNAME}'."
fi
NRSYSMOND_PARAMS="${NRSYSMOND_PARAMS} -n ${NEWRELIC_HOSTNAME:-${HOSTNAME}}"

if [ -z ${NEWRELIC_HOSTNAME} ]; then
  echo "Warning: Variable NEWRELIC_CONFIG_FILE not set. Using default '/etc/newrelic/nrsysmond.cfg'."
fi
NRSYSMOND_PARAMS="${NRSYSMOND_PARAMS} -c ${NEWRELIC_CONFIG_FILE:-/etc/newrelic/nrsysmond.cfg}"

NRSYSMOND_PARAMS="${NRSYSMOND_PARAMS} $*"

echo -e "Starting: nrsysmond ${NRSYSMOND_PARAMS}\n"
nrsysmond ${NRSYSMOND_PARAMS}
